### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by ashwin-raghuraman** [segment-integrations/analytics-ios-integration-nielsen-dcr#26]
Hello,
The iOS app I work on pulls in `1.4.0` version of Segment-Nielsen-DCR through our Podfile.

I was trying to build my iOS app on an M1 mac without setting Xcode to be in rosetta mode. When I do that, the build fails with the following error -
```
ld: warning: ignoring file /Users/ashwin.raghuraman/Library/Developer/Xcode/DerivedData/DCG_iOS-dpypkvuehdhjzgdfwqgxyprrelqo/Build/Products/Debug INT-iphonesimulator/Analytics/Segment.framework/Segment, building for iOS Simulator-x86_64 but attempting to link with file built for iOS Simulator-arm64
Undefined symbols for architecture x86_64:
  "_SEGLog", referenced from:
      -[SEGNielsenDCRIntegration initWithSettings:andNielsen:] in SEGNielsenDCRIntegration.o
      -[SEGNielsenDCRIntegration playHeadTimeEvent:] in SEGNielsenDCRIntegration.o
      ___46-[SEGNielsenDCRIntegration stopPlayheadTimer:]_block_invoke in SEGNielsenDCRIntegration.o
      -[SEGNielsenDCRIntegration track:] in SEGNielsenDCRIntegration.o
      -[SEGNielsenDCRIntegration screen:] in SEGNielsenDCRIntegration.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I do have `arm64` excluded in my Podfile - 
`config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'`

`pod install` works fine when I set Xcode in rosetta mode.

Would anyone please be able to help me figure out how to fix this issue?
